services:
    aliocza_sortable_ui.position.orm:
        class: Aliocza\SortableUiBundle\Services\PositionORMHandler
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
        calls:
            - [ 'setPositionField', ["%aliocza.sortable.ui.position.field%"]]
